"""manage roles

Revision ID: 4621fec11365
Revises: 3c2384c5aae1
Create Date: 2024-04-09 09:28:13.576059

"""

# revision identifiers, used by Alembic.
revision = '4621fec11365'
down_revision = '3c2384c5aae1'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'group_role_map', sa.Column('managed_by_auth', sa.Boolean(), nullable=True)
    )
    op.add_column('roles', sa.Column('managed_by_auth', sa.Boolean(), nullable=True))
    op.add_column(
        'service_role_map', sa.Column('managed_by_auth', sa.Boolean(), nullable=True)
    )
    op.add_column(
        'user_role_map', sa.Column('managed_by_auth', sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role_map', 'managed_by_auth')
    op.drop_column('service_role_map', 'managed_by_auth')
    op.drop_column('roles', 'managed_by_auth')
    op.drop_column('group_role_map', 'managed_by_auth')
    # ### end Alembic commands ###
