"""index_last_activity

Revision ID: bcb4e3b50be6
Revises: 651f5419b74d
Create Date: 2022-11-16 03:30:51.874339

"""

# revision identifiers, used by Alembic.
revision = 'bcb4e3b50be6'
down_revision = '651f5419b74d'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_name'), 'groups', ['name'])
    op.create_unique_constraint(
        op.f('uq_oauth_clients_identifier'), 'oauth_clients', ['identifier']
    )
    op.create_unique_constraint(op.f('uq_services_name'), 'services', ['name'])
    op.create_index(
        op.f('ix_spawners_last_activity'), 'spawners', ['last_activity'], unique=False
    )
    op.create_index(
        op.f('ix_users_last_activity'), 'users', ['last_activity'], unique=False
    )
    op.create_unique_constraint(op.f('uq_users_cookie_id'), 'users', ['cookie_id'])
    op.create_unique_constraint(op.f('uq_users_name'), 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_name'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_cookie_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_last_activity'), table_name='users')
    op.drop_index(op.f('ix_spawners_last_activity'), table_name='spawners')
    op.drop_constraint(op.f('uq_services_name'), 'services', type_='unique')
    op.drop_constraint(
        op.f('uq_oauth_clients_identifier'), 'oauth_clients', type_='unique'
    )
    op.drop_constraint(op.f('uq_groups_name'), 'groups', type_='unique')
    # ### end Alembic commands ###
