"""Add display_name to spawners

Revision ID: f460b0348206
Revises: 4621fec11365
Create Date: 2025-11-05 22:02:38.326220

"""

# revision identifiers, used by Alembic.
revision = 'f460b0348206'
down_revision = '4621fec11365'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'spawners', sa.Column('display_name', sa.Unicode(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spawners', 'display_name')
    # ### end Alembic commands ###
