#!/bin/bash
set -exuo pipefail

docker build -t $DOCKER_REPO:$DOCKER_TAG .
# build onbuild
docker build --build-arg BASE_IMAGE=$DOCKER_REPO:$DOCKER_TAG -t ${DOCKER_REPO}-onbuild:$DOCKER_TAG .

for V in master $stable; do

    docker build --build-arg JUPYTERHUB_VERSION=$V -t $DOCKER_REPO:$V .
done

echo "tagging $IMAGE_NAME"
docker tag $DOCKER_REPO:$stable $IMAGE_NAME
