#!/bin/bash
set -ex

stable=0.8

for V in master $stable; do
    docker build --build-arg JUPYTERHUB_VERSION=$V -t $DOCKER_REPO:$V .
done

echo "tagging $IMAGE_NAME"
docker tag $DOCKER_REPO:$stable $IMAGE_NAME
